### ISSUE TITLE
[M3] Components - Button

### ISSUE THREAD

**Issue by igruszkauy** [material-components/material-design-for-wordpress#325] opened 2022-04-02 13:31 UTC
## Feature description

Update Button component to match M3 style 

Button specs: https://m3.material.io/components/buttons/specs 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Button block is replaced with m3 specs as provided by MDC 
* When the user opens Gutenberg page with m2 component it automatically migrates to M3
* FAB component is not added
* "Large" button retains the name but the styling is based on the FAB "extended" component as described in https://rodydavis.github.io/material-design-lite/components/button/
* "Large" button doesn't have corner radius slider and has fixed min height

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment] 2022-08-23 09:30
Hello @igruszkauy, This is ready for testing. 

1. Add m2 material button block using wp.org version.
1. Add new m3 zip from attachment.
1. Verify m2 is migrated to m3. 
1. Verify m3 button follows specs as mentioned in ticket desc.

Theme: https://s.utkarshpatel.com/material-design-google-theme-9AW4x.zip
Plugin: https://s.utkarshpatel.com/material-design-plugin-fP0CK.zip

**Comment by PatelUtkarsh** [comment] 2022-08-24 05:27
FAB specs: https://rodydavis.github.io/material-design-lite/components/fab/

**Comment by igruszkauy** [comment] 2022-08-26 12:55
Verified via local environment.
M2:
<img width="381" alt="M2 button" src="https://user-images.githubusercontent.com/2902880/186908144-feabab0a-03e3-4264-8a9e-682da7b4f598.png">

Migrated to M3:
<img width="270" alt="normal outlined" src="https://user-images.githubusercontent.com/2902880/186908212-47d4aae3-0070-4b6c-8547-e50b361e6596.png">

1. Raised button is not using primary color for label:

<img width="195" alt="image" src="https://user-images.githubusercontent.com/2902880/186906902-b5b2d3d1-f818-43fb-afb1-b2587b540850.png">

2. If there were large buttons with other variations different than text, when migrated, they are migrated to the normal version with the corresponding variant. I am not sure if this was what we agreed? it looks confusing.
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/2902880/186908089-8c14d7bf-081d-4418-9227-d710fab9a044.png">

**Comment by emeaguiar** [comment] 2022-08-26 16:13
@igruszkauy I updated the color of "Elevated (raised)" to be the correct one.

I can't reproduce 2, all my buttons were migrated to be large, perhaps your version is not up to date? this was a very recent update (merged early today)

<details>
<summary>M2</summary>

<img width="878" alt="Screen Shot 2022-08-26 at 10 54 00" src="https://user-images.githubusercontent.com/1379732/186944768-b9e69c26-7f0d-4423-9bfe-ca4c943e7775.png">
</details>

<details>
<summary>M3</summary>
<img width="721" alt="Screen Shot 2022-08-26 at 10 58 35" src="https://user-images.githubusercontent.com/1379732/186945565-fc4b20fa-cbe6-41d1-acd6-6c7e76809fac.png">

</details>

I did find an issue with border displaying when it shouldn't, I have sent #439 to address both issues

**Comment by igruszkauy** [comment] 2022-08-26 16:33
@emeaguiar can you send me new zips for plugin and theme to check color and test again the large button? I used the zips @PatelUtkarsh  sent today

**Closed** 2022-08-27 04:00 UTC
