### ISSUE TITLE
[FSE] Nav Block

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#142] opened 2021-05-31 19:16 UTC
## Feature description

Nav Block required for full site editing

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment] 2021-11-05 15:46
Duplicate of #229

**Closed by PatelUtkarsh** 2021-11-05 15:46 UTC
