### ISSUE TITLE
FSE style / global style

### ISSUE THREAD

**Issue by jauyong** [material-components/material-design-for-wordpress#225] opened 2021-11-02 15:58 UTC
## Feature description

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by PatelUtkarsh** [comment] 2021-11-05 15:27
Maybe duplicate of #147

**Closed** 2021-11-05 16:02 UTC
