### ISSUE TITLE
[M3] Components - Data Table

### ISSUE THREAD

**Issue by igruszkauy** [material-components/material-design-for-wordpress#328] opened 2022-04-02 13:33 UTC
## Feature description

Update Data Table component to match M3 style

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Data table block is replaced with m3 specs 
* Reference: https://m3.material.io/foundations/design-tokens/overview

![image](https://user-images.githubusercontent.com/2902880/170083273-c6ccbbc5-7190-4fec-8c63-73fcfe410164.png)

* When the user opens Gutenberg page with m2 component it automatically migrates to M3

## Implementation brief

* 

## QA testing instructions

* Download current version of plugin from wp.org, Install add data table and table component.
* Download the latest version of plugin and theme and upgrade and open post in backend:
    * Previous block should be migrated to the new version. 
    * Default table block should be migrated to WP core table.
    * Verify frontend is looking like the one in https://m3.material.io/foundations/design-tokens/overview for material data table.
    * Verify WP core table should look material without rounded edges. (Due to WP core markup is not compatible with material design).

## Demo

* 

## Changelog entry

*

**Comment by mattchungxwp** [comment] 2022-07-12 18:12
Confirm with @rodydavis : Which M3 color tokens to use for the border and header background.

**Comment by PatelUtkarsh** [comment] 2022-07-13 04:33
Hello @rodydavis , 

As per [material site](https://m3.material.io/foundations/design-tokens/overview): 
1. Border is using `--mio-theme-color-surface-variant` which seems like `--md-sys-color-surface-variant` 
2. Table header (TD) is using `--mio-theme-color-surface-1` as background, we don't have suface-1 should we assume `--md-sys-color-surface`?

After doing above data table with generated theme looks like following: 

<img width="894" alt="image" src="https://user-images.githubusercontent.com/5015489/178651189-5b12a038-360c-4757-b712-694772f17c15.png">

If we use 1 and 2 both as `--md-sys-color-surface-variant` then it looks like following:

<img width="874" alt="image" src="https://user-images.githubusercontent.com/5015489/178651279-906d9637-656d-475f-a1b8-40e5bf5d883b.png">

Which m3 token should we use for border and background for `td`?

**Comment by PatelUtkarsh** [comment] 2022-07-14 17:15
Outline for border; Between headers use on surface; Background is `--md-sys-color-surface`.

**Comment by PatelUtkarsh** [comment] 2022-07-15 06:01
Hello @rodydavis, 

Here is a table heading with surface variant. (Border inside header is using on surface variant)

https://user-images.githubusercontent.com/5015489/179160188-dce0e607-aecf-4e8b-974b-4c71ecfb3cf7.mp4

If we use table heading background as surface, it matches the page background. See below:

<img width="1924" alt="image" src="https://user-images.githubusercontent.com/5015489/179159911-7872f7b8-856f-4ed7-9553-79a9fdb08e56.png">

While m3 reference site is using `surface-1`; Should we continue to use `surface variant`? 
<details><summary>Screenshot for reference:</summary>
<p>

<img width="1837" alt="image" src="https://user-images.githubusercontent.com/5015489/179160610-241201e4-f9fb-40bb-8f9a-fb344ab49c1b.png">

</p>
</details>

**Comment by PatelUtkarsh** [comment] 2022-07-26 17:55
@rodydavis to provide designer feedback on the ticket.

**Comment by PatelUtkarsh** [comment] 2022-07-26 18:01
Confirmed on call: Okay to use surface variant.

**Comment by felipebochehin87** [comment] 2022-07-29 09:02
@PatelUtkarsh 

* when I upgrade my local site to use the latest version, I see issues in the table borders. They're not rounded. I manually changed the Global Corner Styles, but I still see the square borders;
* the footer doesn't have the same background color as the header. The header is being automatically set to a color, but the footer is not. 

![settings local](https://user-images.githubusercontent.com/96055551/181723713-a30f397e-2fdf-4cd7-9da2-469e1f31e3b5.png)

![table local](https://user-images.githubusercontent.com/96055551/181723763-e57a7683-43ef-42d1-81d6-66bc4144f66b.png)

**Comment by PatelUtkarsh** [comment] 2022-07-29 09:28
@felipebochehin87 Is this material block or WP core table block?

**Comment by felipebochehin87** [comment] 2022-07-29 10:25
@PatelUtkarsh you're right, I checked the wrong table on local, sorry. It is working in dev and in local using the correct table. Thanks for pointing that out. Moving to UAT.

**Comment by igruszkauy** [comment] 2022-07-31 14:23
I installed locally and this is what I am seeing after updating. @felipebochehin87 can you please post screenshots of how you are seeing the new components migrated? I am not sure if I am doing something wrong
<img width="782" alt="image" src="https://user-images.githubusercontent.com/2902880/182030851-f16dcf1c-2e59-4083-8c95-901d34111bd1.png">

**Comment by felipebochehin87** [comment] 2022-08-01 11:53
@igruszkauy here's a video of how I tested in my local site (BTW, I used "Data Table (Material)" to test this).


https://user-images.githubusercontent.com/96055551/182142194-3777bf11-f506-4899-872d-27f26d857158.mp4

**Comment by felipebochehin87** [comment] 2022-08-02 11:26
In a fresh install, the new table (Material) is not displaying the round corners, the lines between the cells... This is working for me in an existing site.

![image](https://user-images.githubusercontent.com/96055551/182363656-787dee9f-c8e0-46eb-ae07-9aee0a1e9f84.png)

**Comment by PatelUtkarsh** [comment] 2022-08-02 12:47
Hello @felipebochehin87, Does this work post colour generation from customizer and saving it? 

<img width="303" alt="image" src="https://user-images.githubusercontent.com/5015489/182377615-4b942a40-2b51-4f99-a237-03a37f2c9e19.png">

I tested m3 zip with fresh WordPress and post color generation in customizer this seems to work for me. Can you give it a try? 

Steps: 
1. Fresh installation of WP.
1. Add theme and plugin zip. 
1. Activate theme and plugin. 
1. Create post with material data table, Border is not visible. Save draft or publish. 
1. Go to `/wp-admin/customize.php` 
1. Material design option -> Color Palette.
1. Click random generation icon or pick any color. 
1. Save 
1. Go back to post in backend and refresh. Verify frontend.

**Comment by igruszkauy** [comment] 2022-08-05 23:30
Works as expected, besides the need of choosing source color if coming from a new install.

**Closed** 2022-08-24 05:28 UTC
